- name: Check if host is reachable
  wait_for:
    timeout: 0
  register: connect_rs
  ignore_unreachable: yes

- when: connect_rs is unreachable
  name: Try first login and change the password
  delegate_to: localhost
  expect:
    command: sshpass -p {{ auth_first_login_password }} ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }}
    timeout: 60
    responses:
      "Current password:": "{{ auth_first_login_password }}"
      "New password:": "{{ ansible_password }}"
      "Retype new password:": "{{ ansible_password }}"

- name: Setup public key authentication
  authorized_key:
    state: present
    user: "{{ ansible_user }}"
    key: "{{ auth_public_key }}"

- name: Collect facts
  setup:
