---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: local-storage
  name: local-path-provisioner
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: local-path-provisioner
      chart: local-path-provisioner
      version: 0.0.19
  interval: 1h
  
  values:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi

    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /local-path
      - node: agent-storage-pi4
        paths:
          - /mnt/md0/local-path

    storageClass:
      name: local

    configmap:
      name: local-path-config
      teardown: |-
        #!/bin/sh
        while getopts "m:s:p:" opt
        do
            case $opt in
                p)
                absolutePath=$OPTARG
                ;;
                s)
                sizeInBytes=$OPTARG
                ;;
                m)
                volMode=$OPTARG
                ;;
            esac
        done

        base=$(dirname $absolutePath)
        dirname=$(basename $absolutePath)
        archivePath="$base/archived-$dirname"
        mv $absolutePath $archivePath
    
