apiVersion: v1
kind: Secret
metadata:
    namespace: ingress-system
    name: cloudflare-apikey
type: Opaque
stringData:
    apikey: ENC[AES256_GCM,data:3KQSjh0xBCnFPB74IvEvVWuSCQGEkIZrduGpMvZTjGP3XqseuNnZs9HO0606P5R/8efgEvxZajM=,iv:a5yZGINWxvWKA3204z7wXbqs+YSkDvKXi63W5xgc5KM=,tag:LDLRSrtnSEQKqThuysLtUQ==,type:str]
    #ENC[AES256_GCM,data:oc6C4oj8wTPYjxjNHpuNtg+1Fc7viLs7dx16pIg5E+9JrkHa53WlhDA=,iv:9fHKW0d+waAFqXFvui5NiTWHbsvdjlqnWZNoPuhO9Vo=,tag:4hjp7zKucrN+aoKzORnFTw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-06T18:23:03Z'
    mac: ENC[AES256_GCM,data:46rvgMe18u+r27JoZEF2MBQbtsOPcDEvt65htcXVlSb3ZyBciuMZupaZS7TAY22FX7iQpSIXPBXsZL3bzoM2oypKxxAQvJBPQCxbSANQtWDWQZ5KkkuB4987SyPL92STd5vkGidn4/OAGqIYsGqsQGquYNweNqRbWBT1mXaWa6E=,iv:MrX/9LYogKD6zWrT07LK/0uuS0oKU6PMRrcV3uKV4ls=,tag:caHRuWRwrFRlhPUcMKKF7g==,type:str]
    pgp:
    -   created_at: '2021-03-06T18:23:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA7Y4wydbWsR8EAf/cDCr5DVMauB97HyDeMP+QqTDmZYw7unsiYgqkwZJxCPU
            r+PHzG05I5zbWTngBWE0tz3cKscGLH1mAShXaeZiEL8kEvudhoTFxwq3YBOTITyt
            VZDpP+8Dj5a2cSWG4ZBqsDxjTfXHtnHkl/VA33TivW3df4UEvvaTG5tEUZ8iRwBw
            Ge4XZBnB6jMb8uAO63yx0wyCwYuecJr54HfOMFQvQGfnDBXFgiX8Q6OY9HHSzDmB
            Jx3hJqgD8S34j9JLSz8HNb9pb5V7c7p2CRS+EU63s642bWRyYi/nlUM+vk9uefWb
            QxcIkOx1PJXxeI3aCrTo49g1w7n0fiofr1Q6QGhraAgAnuM/CjIPRw3QsTspvxTy
            ywFEB84ZTHqnaXpZPINZzMjLxZJy1lhhsXQ6cBK807WGRTmJxiyf5wEV/zB9P5rE
            awrXJe+7WgvnmFAmJ9zo/fuVdcM8QtqVUVzFRrJNDxB83y/BsqvfF5kBUvT3O98W
            8YMIgCLwVe/mKpEgOiMBK1Zr/eJLv60cWvbZzCReI0AfTfWKt6xCNh6AVJPI2s1O
            Qn07jPX3/rB78DkXgwJOfrHhg+dBotHuaHUPBwekee7xVsrEC1i8V2uRUKYA8eHM
            lzaQmkK+LTeMVUJYJVlt2kNODStiEpQDXkIbMWHAgzCf1f+RTAs4SnJ/3F1qGeOY
            pdJeAdgH6k68U5bV8kmnlsI0DBeQa4CkN5Y/HaXvckuyfivA6WHshIOVvPW2NfIo
            xdAgaeWJpmUYiLhYNLvTJd/OkNZV9wKF2hpOXYUs48UkEKXSpbUMzcDA3re5jxM6
            Dg==
            =b5CF
            -----END PGP MESSAGE-----
        fp: E63E2F1B2C5A84E8286E2D23ABFED62BADD73CB4
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword)
    version: 3.6.1
