apiVersion: v1
kind: Secret
metadata:
    namespace: ingress-system
    name: cloudflare-apikey
type: Opaque
data:
    apikey: ENC[AES256_GCM,data:ef0lacpZ2E1IYQxIlbeayzdUYbnpUOzhlpFa0uGkamk9PJ5Q7jgS2VNYlussmSSvMm2D2QeLfaI=,iv:dSqtJodDkWZbsG4QpVwoZIoXt98vKb9IScClCYj9/yw=,tag:OlezW7St9pjcnUQ0w5+j9w==,type:str]
    #ENC[AES256_GCM,data:4x2tXB5CEkCECx3D06OCNttUMXSLN3zpeKfeXfFtgYv5M5cP9/58DFs=,iv:ddg4VItebwN90RWjnaOypzh81Nx/F4TTekYYyoAw/5o=,tag:E7X9Za8WVGHvboOncn4yIw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-06T19:02:24Z'
    mac: ENC[AES256_GCM,data:Vm/46rfYXIEEK0x9anuhANV1JQ6dbZDys89eDjSOnlpM7I3aBYMFbMHksfXIsi+G3LBCuLnlfAZakupephUOswOgEZVtCcBH2Ru8IKXq/6d933EzH3xvHbfqUuPGSnm0x2h2pzyZPzMxWTZyaCVh/U8r1uhmZ0K1vy3EnyMBrAU=,iv:QFGnnrjNvOaAC/YVqsUc3QbjFl2pwqsvQAQx52N/2F8=,tag:WEj9UFLTAwRvagTCZqrWAA==,type:str]
    pgp:
    -   created_at: '2021-03-06T19:02:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIOA7Y4wydbWsR8EAf/Uu2vIfMoBGvvPBJphl7R7h5a29uVylxNPYZ3ntNtOCC/
            mGNkr3WAbyI133lC4A2AYfemxlaNDBoFY2U7b/seoxE1G7NFQf/WzlShSt12QeqD
            0cbGI1XG9k3wBHolrPRb+v21n3faDPMaOyPn8Ow2K4jlE0Y+V0+78aOQHjqQqJsp
            MOiiJ0ESxyyHwgNxs1eS/KreBr687h0XNg+wWdLuJSvjdgzTBUDbl5D3QxBT1skB
            MOFJIrjRujLA4m4xtRzmitsyOGXDJ+fIi9NAfVS/DCwdQ4y1v5BtJT15vQtGlE+d
            VoaDM6/TYMWgN/LAf8vGLl80JMzgnJ8/LQx9GxESFggAybNIWKsEk9OqfQ9rAcqV
            +mAXVTRoeQL3OpfOyc6JpRylZZ1ZkX3/94PMWNiounjKpAopfSjJl+jN5LGUHQD2
            pyYoHfRBOu+gJIfz60l7vjgkSvvDwetIPKil1Nl8kgHr5jcjglz0DffLHrWQ4aKm
            2w0bR/JtTZdjNU9/tFspSTDMCT14XhQOQqkh7iqk+rMNBgj1vHCKVSdtFJjkSRjX
            hUwUgPYFVEFxZdx7KOqT9Tg0TZnM0OrqhkyD/Wy4fhII0zJ0xJPQm3Y9a0fh7Sbw
            Wa6CskedHYhISHKRM3GELEahZUclHov13tRm1rROKYLOIkGqvUo893Fk0Ar6yjyh
            1dJeAUvQB5RPXHtmI4UtvRn3Wt3y6J6lL9jCwXKz8XSP/GTdCeLAre4c+NrllLxN
            Wh0rxsnm/Q2L84KXQGs09MC9YVsbS27JB4bpBWnNtR/bE512ahrEpd3SDPXqR4Sj
            jQ==
            =5v4O
            -----END PGP MESSAGE-----
        fp: E63E2F1B2C5A84E8286E2D23ABFED62BADD73CB4
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword)
    version: 3.6.1
