---
- name: Enable cgroup via boot commandline if not already enabled for Centos
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    register: activate_cgroup
  
- when: activate_cgroup is changed
  name: Reboot
  reboot:
