clusterAddresses: 192.168.255.200-192.168.255.210
forwardIP: 192.168.255.200
rootDomain: timtorchen.com

nfs:
  server: 192.168.255.100
  path: /mnt/md0

label:
  agentStorage:
    kubernetes.io/hostname: agent-storage-pi4

taint:
  mayPoweroff:
  - key: "poweroff"
    effect: NoSchedule
    value: "true"
    operator: Equal

storageClass:
  cluster: longhorn
  local: local-path
  nfs: nfs-client

certificate:
  staging: ingress-system/wildcard-certificate-secret-staging
  production: ingress-system/wildcard-certificate-secret

localProvisioner:
  resources:
    requests:
      cpu: 0.1
      memory: 100Mi

ingress:
  publicAnnotations:
    kubernetes.io/ingress.class: nginx
  internalAnnotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.0.0/16"

longhorn:
  hostname: longhorn.timtorchen.com
  resources: {}

minio:
  endpoint: minio.baremetal-system:9000
  hostname: minio.timtorchen.com
  resources: 
    requests:
      cpu: 500m
      memory: 500Mi

# adguard:
#   hostname: adguard.timtorchen.com
#   storage: 500Mi
#   resources:
#     limits:
#       cpu: 500m
#       memory: 500Mi
#     requests:
#       cpu: 100m
#       memory: 100Mi

# wireguard:
#   hostname: wireguard.timtorchen.com
#   storage: 100Mi
#   resources:
#     limits:
#       cpu: 200m
#       memory: 500Mi
#     requests:
#       cpu: 100m
#       memory: 300Mi

# openvpn:
#   storage: 10Mi
#   resources:
#     limits:
#       cpu: 0.5
#       memory: 100Mi
#     requests:
#       cpu: 0.5
#       memory: 100Mi

nextcloud:
  hostname: nc.timtorchen.com
  storage: 250Gi
  resources:
    requests:
      cpu: 2
      memory: 1Gi

nextcloudPostgres:
  storage: 2Gi
  resources:
    requests:
      cpu: 0.1
      memory: 100Mi

nextcloudRedis:
  storage: 100Mi
  resources:
    requests:
      cpu: 0.1
      memory: 100Mi

jellyfin:
  hostname: jellyfin.timtorchen.com
  config:
    storage: 1Gi
  media:
    storage: 50Gi
  resources:
    requests:
      cpu: 1
      memory: 500Mi
  
bitwarden:
  hostname: bitwarden.timtorchen.com
  storage: 500Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  server:
    storage: 8Gi
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  
  altermanager:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

  pushgateway:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

grafana:
  hostname: grafana.timtorchen.com
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

blog:
  hostname: timtorchen.com
  hostnameDraft: draft.timtorchen.com
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

