# Helm plugins needed: helm-diff, helm-git, helm-secrets

bases:
- common/repo.yaml

environments:
  default:
    values:
    - config.yaml
    secrets:
    - secrets.sops.yaml

templates:
  default: &default
    values:
    # values file end with .gotmpl, will be rendered as a template
    # values file end with .yaml, will be rendered verbatim
    - releases/{{`{{ .Release.Name }}`}}/values.gotmpl
    
  raw: &raw
    chart: incubator/raw
    version: ~0.2.3
    values:
    - raw/{{ `{{ .Release.Name }}` }}.gotmpl

commonLabels:
  group: all

releases:
- name: metallb
  <<: *default
  namespace: baremetal-system
  chart: stable/metallb
  version: ~0.12.0
  labels:
    type: system

- name: rancher-local-provisioner
  <<: *default
  namespace: baremetal-system
  chart: rancher-local-provisioner/local-path-provisioner
  version: 0.0.19
  labels:
    type: system

- name: nfs-client-provisioner
  <<: *default
  namespace: baremetal-system
  chart: stable/nfs-client-provisioner
  version: 1.2.11
  labels:
    type: system

- name: kured
  <<: *default
  namespace: baremetal-system
  chart: kured/kured
  version: 2.3.1
  labels:
    type: system

- name: minio
  <<: *default
  namespace: baremetal-system
  chart: minio/minio
  version: 8.0.9
  labels:
    type: system

- name: longhorn
  <<: *default
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.1.0
  labels:
    type: system

- name: longhorn-s3-secrets
  namespace: longhorn-system
  <<: *raw
  labels:
    type: system

# - name: adguard-home
#   <<: *default
#   namespace: baremetal-system
#   chart: k8s-at-home/adguard-home
#   version: 2.2.0
#   labels:
#     type: system

- name: nginx-ingress
  <<: *default
  namespace: ingress-system
  chart: nginx-ingress/ingress-nginx
  version: ~3.15.2
  labels: 
    type: system

- name: cert-manager
  <<: *default
  namespace: ingress-system
  chart: cert-manager/cert-manager
  version: v1.1.0
  labels:
    type: system
  
- name: cert-manager-crd
  <<: *raw
  needs:
  - ingress-system/cert-manager
  namespace: ingress-system
  disableValidation: true
  labels:
    type: system

- name: prometheus
  <<: *default
  namespace: monitor-system
  chart: prometheus/prometheus
  version: ~11.10.0
  labels:
    type: system

- name: grafana
  <<: *default
  namespace: monitor-system
  chart: grafana/grafana
  version: 6.2.1
  labels:
    type: system

# - name: openvpn
#   <<: *default
#   namespace: system
#   chart: stable/openvpn
#   version: 6.16.16

# - name: wg-access-server
#   <<: *default
#   namespace: system
#   chart: wg-access-server/wg-access-server
#   version: ~0.3.0

- name: bitwarden-rs
  <<: *default
  chart: k8s-at-home/bitwardenrs
  version: 2.0.0
  labels:
    type: app

- name: bitwarden-rs-secrets
  <<: *raw
  labels:
    type: app

- name: nextcloud
  <<: *default
  chart: nextcloud/nextcloud
  version: 2.3.2
  labels:
    type: app

- name: nextcloud-postgres
  <<: *default
  chart: groundhog2k/postgres
  version: 0.2.7
  labels:
    type: app

- name: nextcloud-redis
  <<: *default
  chart: groundhog2k/redis
  version: 0.2.8
  labels:
    type: app

- name: nextcloud-test
  <<: *default
  chart: groundhog2k/nextcloud
  version: 0.4.0
  labels:
    type: app-test

- name: jellyfin
  <<: *default
  chart: k8s-at-home/jellyfin
  version: 4.3.1
  labels:
    type: app

- name:  blog
  <<: *default
  chart: timtor/blog
  version: ~0.1.0
  labels:
    type: app

- name: blog-draft
  <<: *default
  chart: timtor/blog
  version: ~0.1.0
  labels:
    type: app
