hostname: timtorchen.com
forwardedIP: 192.168.255.200

metallb:
  publicAddresses: 192.168.255.200/32
  localAddresses: 192.168.255.201-192.168.255.210

certmanager:
  wildcardCert:
    name: wildcard-certificate-secret
    dnsNames:
    - "timtorchen.com"
    - "*.timtorchen.com"

nginx:
  exportIP: 192.168.255.200
  defaultCert: system/wildcard-certificate-secret

nfsclient:
  nfsServer: 192.168.255.150
  mountPath: /mnt/ssd
  storageClassName: nfs-client

coredns:
  exportIP: 192.168.255.201
  clusterIP: 10.43.0.10
  extraRootPlugins:
  # k3s current do not support customization of coredns
  # Manually configure nodes and corresonding IPs
  - name: hosts
    parameters: /etc/coredns/node.hosts
    configBlock: |-
      reload 1s
      fallthrough
  # local domain configuration
  - name: file
    parameters: /etc/coredns/timtorchen.com.db timtorchen.com
  
  Files:
  - filename: node.host
    contents: |
      192.168.255.101 client1
      192.168.255.150 master
  - filename: timtorchen.com.db
    contents: |
      timtorchen.com.    IN  SOA  timtorchen.com timtorchen.gmail.com 2015082541 7200 3600 1209600 3600
      timtorchen.com.    IN   A   192.168.255.200
      *.timtorchen.com.  IN   A   192.168.255.200

  replicaCount: 3
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

wireguard:
  storage: 100Mi
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi

openvpn:
  storage: 10Mi
  resources:
    limits:
      cpu: 0.5
      memory: 100Mi
    requests:
      cpu: 0.5
      memory: 100Mi

nextcloud:
  replicaCount: 1
  storage: 100Gi
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

mariadb:
  storage: 2Gi
  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 300Mi

jellyfin:
  # media 
  existingClaimMounts:
  - name: nextcloud
    mountPath: /nextcloud
    existingClaim: nextcloud-nextcloud
  # web static file, config, and database
  storage: 1Gi
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 1
      memory: 500Mi
  
bitwarden:
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  server:
    storage: 8Gi
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  
  altermanager:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

  pushgateway:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

grafana:
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

