clusterAddresses: 192.168.255.200-192.168.255.210
publicIP: 192.168.255.200
localdnsIP: 192.168.255.201
personalServiceIP: 192.168.255.202

rootDomain: timtorchen.com

certificate:
  wildcardCert:
    name: wildcard-certificate-secret
    fullname: system/wildcard-certificate-secret
    dnsNames:
    - "timtorchen.com"
    - "*.timtorchen.com"

ingress:
  public: nginx
  personalService: personal

nfsclient:
  nfsServer: 192.168.255.150
  mountPath: /mnt/ssd
  storageClassName: nfs-client

pihole:
  hostname: pihole.timtorchen.com
  storage: 500Mi
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi

wireguard:
  hostname: wireguard.timtorchen.com
  storage: 100Mi
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi

openvpn:
  storage: 10Mi
  resources:
    limits:
      cpu: 0.5
      memory: 100Mi
    requests:
      cpu: 0.5
      memory: 100Mi

nextcloud:
  hostname: nextcloud.timtorchen.com
  replicaCount: 1
  storage: 100Gi
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

mariadb:
  storage: 2Gi
  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 300Mi

jellyfin:
  hostname: jellyfin.timtorchen.com
  # media 
  existingClaimMounts:
  - name: nextcloud
    mountPath: /nextcloud
    existingClaim: nextcloud-nextcloud
  # web static file, config, and database
  storage: 1Gi
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 1
      memory: 500Mi
  
bitwarden:
  hostname: bitwarden.timtorchen.com
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  server:
    storage: 8Gi
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  
  altermanager:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

  pushgateway:
    storage: 2Gi
    resources:
      limits:
        cpu: 0.1
        memory: 100Mi
      requests:
        cpu: 0.01
        memory: 30Mi

grafana:
  hostname: grafana.timtorchen.com
  storage: 100Mi
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

blog:
  hostname: timtorchen.com
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
