# Helm plugins needed: helm-diff, helm-git, helm-secrets

bases:
- common/repositories.yaml

environments:
  default:
    values:
    - config.yaml
    secrets:
    - secrets.enc.yaml

templates:
  default: &default
    chart: stable/{{ `{{ .Release.Name }}` }}
    values:
    # values file end with .gotmpl, will be rendered as a template
    # values file end with .yaml, will be rendered verbatim
    - releases/{{`{{ .Release.Name }}`}}/values.gotmpl
  
  system: &system
    <<: *default
    namespace: system
  
  nginx: &nginx-ingress
    <<: *default
    namespace: system
    chart: stable/nginx-ingress
    version: ~1.41.0
    
  raw: &raw
    chart: incubator/raw
    version: ~0.2.3
    values:
    - raw/{{ `{{ .Release.Name }}` }}.gotmpl

releases:
- name: metallb
  <<: *system
  version: ~0.12.0

- name: public-ingress
  <<: *nginx-ingress

- name: personal-ingress
  <<: *nginx-ingress

- name: cert-manager
  <<: *system
  chart: jetstack/cert-manager
  version: ~v0.16.1
  
- name: cert-manager-crd
  labels:
    install: crd
  <<: *raw
  namespace: system

- name: adguard-home
  <<: *system
  chart: k8s-at-home/adguard-home
  version: ~2.2.0

- name: nfs-client-provisioner
  <<: *system
  version: ~1.2.8

- name: prometheus
  <<: *system
  version: ~11.10.0

- name: grafana
  <<: *system
  version: ~5.5.0

- name: openvpn
  <<: *system
  version: ~4.2.3

- name: wg-access-server
  <<: *system
  chart: place1/wg-access-server
  version: ~0.3.0

# Chart: unofficial-chart
- name: bitwarden-rs
  <<: *default
  chart: cdwv/bitwarden-k8s
  version: ~0.1.5

- name: nextcloud
  <<: *default
  chart: ./charts/nextcloud
  version: ~1.12.0

# pure yaml deployment for nextcloud-mariadb
- name: mariadb
  <<: *raw

# Chart: unofficial chart
- name: jellyfin
  <<: *default
  chart: brianmcarey/jellyfin
  version: ~0.1.0

- name:  blog
  <<: *default
  chart: timtor/blog
  version: ~0.1.0

- name: blog-draft
  <<: *default
  chart: timtor/blog
  version: ~0.1.0