---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-redis
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: groundhog2k
      chart: redis
      version: 0.2.9
  interval: 1h
  values:
    resources:
      requests: 
        cpu: 100m
        memory: 100Mi

