---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blog
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: blog
      # renovate: registryUrl=https://timtorchen.github.io/blog
      chart: blog
      version: 0.1.0
  interval: 1h
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns: public
        external-dns.alpha.kubernetes.io/hostname: timtorchen.com,www.timtorchen.com
        external-dns.alpha.kubernetes.io/target: cname.timtorchen.com
      hosts:
      - host: timtorchen.com
        paths: [/]
      - host: www.timtorchen.com
        paths: [/]
    
    serviceAccount:
      create: false
    
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    
