- name: Set hostname
  hostname:
    name: "{{ init_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ init_timezone }}"

- name: Temporarily stop auto-upgrade
  systemd:
    state: stopped
    name: unattended-upgrades
  ignore_errors: yes

- name: Remove unused packages
  apt:
    state: absent
    autoremove: true
    purge: true
    name: "{{ init_apt_remove }}"

- name: Install packages
  apt: 
    name: "{{ init_apt_install }}"

- name: Restart auto-upgrade
  systemd:
    state: started
    name: unattended-upgrades
  ignore_errors: yes

