---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: kube-system
  name: metallb
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: stable
      version: 0.12.1
      chart: metallb
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.5
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.5
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.255.200-192.168.255.210
