ansible_password: ENC[AES256_GCM,data:g1KI7+PbiXs=,iv:sCNefVB/+30Y8e0UnvReb/RRvaqU5z1rmmY18yIn1ps=,tag:tD0LSxAN9GLwQHRC+hwUUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-31T17:53:47Z'
    mac: ENC[AES256_GCM,data:JK6h9gEtuxbY90y1CkRey+sd9FLSF37k8bC5TDJOtQPD5QMqxS70hlWu4ZgbDzlnyPnMgeInhteJEdDZCHZh3ZOAhbmbuy81IDFk9rgTuVQQsWbkM+Y4y8wnxg8fcbOiGP6XapKQpzVrDHfGmEg6fxuJu/R8GDEI0OHU/9NqkUk=,iv:A5Jlh52da8WwflenVYuj9MfB2uP4IOuQm1Ejy93KeKU=,tag:MRsf5NP0Xbk28z0X6Wc0HA==,type:str]
    pgp:
    -   created_at: '2020-12-16T07:23:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAx6PzfjhAf77AQv/e7+feQ0flgoUnsF6FlD1tWxBe9lZgj4E3rlxYG6lSZhB
            ceKxzjLYRawfvjtzv7exxlKKC6jkuuleyFBYWNZtXz5hnMYLvQF1uJ0MT04lqKxo
            6CMfCpPsySwarMfuylVldYh+oBAutGEoTfzxGGiwxFjbm8pEt4JtyN9tbWlYMWIV
            HZXIRW3+sIZ+dLkk07kNiB13Dj2hJ2+dYFXj7kAG6ICk0CB19S6dsrNGRI9j2axb
            1LOL2LikRs9EKxdnB1T6GwH0z1a2VDXsPAZuZk7y2sQ3b7J/9Yzy1N4qeZQSe/B2
            6iKRjCrXEJWmHagNZ1ThQSTZlsTG6alYE8RBtO2yf+p9Zs8r2znri3X1XuPEv0Zm
            3Vg34ys7PPLlVrYEo3LMEo3YS7jsk2UePwCE9TnEe5fm1DZsdzca1Z0b1eZaVQXa
            ki7NhntQ6OKbXBvAyPyTUT8UJ6hwy2idGkRy5VpmlKaTA089BR2qvEksi7hma9fN
            HloJrOF3B9gGk5R2q5yq0l4B4QNaRoMHEox5/1ceTtT/mRwiP064nEB1WSabG0wo
            sr+jhNzd6i5fYWiATlKOJlKJ9WIfBrhtkjHpTjNnkjROpEjWEMsovcdqaUqD0b4T
            XbE4Dr+/llhfGwKFY7nv
            =qhER
            -----END PGP MESSAGE-----
        fp: F1801D0F038E98092972FDDBAE404DD02B551819
    unencrypted_suffix: _unencrypted
    version: 3.6.1
