---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: k8s-at-home
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bitwardenrs
      version: 2.1.11
  interval: 1h

  values:
    image:
      repository: bitwardenrs/server
      tag: 1.18.0

    persistence:
      enabled: true
      storageClass: ceph-fs
      size: 500Mi

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.0.0/16"
      hosts:
        - host: bitwarden.timtorchen.com
          paths: [/]

    resources:
      requests:
        cpu: 100m
        memory: 100Mi

    bitwardenrs:
      domain: https://bitwarden.timtorchen.com
      signupsAllowed: true
      admin:
        enabled: true
        disableAdminToken: false
        existingSecret:
          enabled: true
          name: bitwardenrs-secret
          tokenKey: admin-token
