apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-config
spec:
  storageClassName: ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals
spec:
  storageClassName: ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
