apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: ingress-system
  name: nginx-ingress
spec:
  namespaceSelector:
    matchNames:
      - ingress-system
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  endpoints:
    - port: metrics
