---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: kube-system
  name: kured
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: kured
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.4.3
  interval: 1h
  values:
    image:
      # Unofficial image
      repository: raspbernetes/kured
      tag: 1.6.1

    configuration:
      timeZone: Asia/Taipei
      startTime: 13:00
      endTime: 17:00
      period: 1h0m0s # default check period
      rebootDays: [mo,tu,we,th,fr]

    service:
      create: true
      port: 8080
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
