---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: monitor-system
  name: thanos
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: banzaicloud
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.4.2
  interval: 1h
  values:
    image:
      repository: raspbernetes/thanos
      tag: v0.17.1
    objstoreSecretOverride: thanos-object-store


