---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgres-data
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
