---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: nextcloud-postgres
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
