apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secret
type: Opaque
stringData:
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:kuNO6mR2yGkwojcFF1lKHIHAvr+1A+O1,iv:j5qIn00bjbE3Qq0Dl8Pgjusf3OF3/0jfes3ULSVDQOk=,tag:uKSSoaU4tyWpn+iZCghmCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-11T06:21:15Z"
    mac: ENC[AES256_GCM,data:FhCONYIWbs8O1ApUOgv+21U7vY8RTK1MxkoXStWpl2PDqiVvrKum4YXj1FNNVrY2ohzAjk2Wx8zSJskTKo9pxGv7UAqYCUjEFXrHJIhL/UxjetC4V+Fl+8ioM4Fopqbyuz70K4d/3zG3UecCKiEiaJXePBIY1j8tPsHK7eoyKYM=,iv:HskvOp+KHy/Zn/WxVSvL118hHkKs671BpT5kuzAtLxQ=,tag:TCvBBM6cBeE4BV7XvDlGbQ==,type:str]
    pgp:
        - created_at: "2021-06-11T06:21:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAv/TTfwqJuuBpxMaAZpkITwlH8UNdwgtV7yH5LKI0toOMPs
            MY1JHgf9U2657Y80fuXN7zcb/ai/nC3FqSTYoBCBf/GZkqLFegKyuj2X1vevcsdv
            fnxRjkp8ycJ8GqNEWLvVNRnTSfQ8c5Sxfs5N3EhETyCd0P7MeOse8xtmqs8EkBT+
            g/WDDQzEL2JPx95IlL7drjil9ply3igGnvihUwUgS3t65UlcsP9PAoL6OrU9xFEY
            qMqxth7z0Fceb59krfYb8YW8DNj/QXvXdR7fVvdR15wTWK3E1cLyJXH7/FNjiJWc
            KKUiYkvxRCVPt87htO5k4+34UFH5r4YpF1lDIDFoMP726/Cvmyd5crZs4wyAoJ7J
            Ki6SMh7BMFl0R5OdQhS8gPrFppCkT772G/2A3SdpBDKT/xWwzHjXxoUoChIlkVmu
            c/S3Gv9oxawLSM+5Yn6xAej9c7OZJwtTR6gZESYjXxJLiGlc5Sf+rfrjlEnJT6ev
            m1lbVfPKIr/gmdFSdW8JC/9+5drh5sB+FXAFjcbsuB7yRhUSggmjm9oToF/bSNWW
            VsFjvu1HqB+Gakjt2Sui+RRsXOWl5dJqdwlYa1ZMxdx9HwxQAkgbx6ViJdmHxEsj
            4EvWg5UcYE44Qee5Ab4fh6a+c1Fop937l37Wo/VVITvXTPB+AeJ5BTRhiEXBmr7f
            21n4gg8LZoivQMLUuqoC3yUn9sJT3UglL/KVbOEzYfNVpUce7fJYF4D4+WbtUpVU
            2UOZGTvorQt+jP62uR/chg4rbId2b+aF5wBoo4sU1CNPiAFXqy9JHK1qXQo0Q1p0
            ZMRZfZZQXAk97V93YtcmhN7RYb44r9LS13gX7rdhyqOJag7VQqUyDx2Hiy1aDcPX
            wS1X4oOquwv6/5YQdmN+mmcL/P08/AoD42PVLJ0hzSFPyrl/2mLG2j/aMDPiKVnQ
            h0KH+fXpUhiZxkf/stm/j/3rj+v1O0HYviiPTNMAk5iuuu15bHm9htOEQPmI3oiz
            P44VcxFtALeOMyq0xKkjteDSXgFm1FNSUka7xYhTBTwU9triTqhoN9KZODsJVrF2
            UfwJTxSSFuhRX1YEt1ncJsLL7OFxBtON1Ty2a/UzxhI1Dqhcp5vqbfxKpAdg8oCC
            rwkT1xx2G8BZjidYMu9KAGs=
            =dxzD
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
    version: 3.7.1
