---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: app
spec:
  interval: 10m0s
  path: ./gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  decryption:
    provider: sops
    secretRef:
      name: gpg-secret