---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: crd
spec:
  interval: 10m0s
  path: ./gitops/crd
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: source
spec:
  interval: 10m0s
  path: ./gitops/source
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: infra
spec:
  interval: 10m0s
  path: ./gitops/infra
  prune: false
  dependsOn:
    - name: source
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: gpg-secret
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: app
spec:
  interval: 10m0s
  path: ./gitops/app
  prune: true
  dependsOn:
    - name: source
    - name: crd
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: gpg-secret
  ## TODO: keep track of some issues in order to seperate CRD from app
  ## eg. cert-manager, CRD is only in github release
  ##     longhorn, planning to do in v1.2 milestone
  # validation: client
