apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: cloudflare-api-token
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:+4LuCxTKWz3nS0K27FDi2W/jsarOk18ztdtSt0NqLibOB8Znkes4dyea5Lpmiwz6Rky4VS2eQB8=,iv:GpyqTr84tPsBuFuA96bmcGWq/asjw20yXgS8RvS8FLQ=,tag:PVM1CgKnvBrwjL944HG4og==,type:str]
    #ENC[AES256_GCM,data:RjmFLfjS24dRghpFSnRmvhCYRwjtYTi8qBwdEVE8MWatv55QtxXMdMg=,iv:eFJTNPnmCCLCmFOV+iaCkZ5Nxf3DwyHp935FPgBEueM=,tag:C+BDLrv6WZkgjAvydZ8LJw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-24T16:45:28Z"
    mac: ENC[AES256_GCM,data:fBjDQdnhxkCCJ14mVQdEws591INulAkQgjeCj4sjkqncOj/luXR9tr0V8mPHvR2Kvd6/IvbW5DZ339oTu+Jl0nd2UUk338rb1mGkMOxFm5xQFXF/94wOCVgeI0fYIMm3k1vPorCQppwcNcO4PN2qclOkT6toxOrGZ2viIOqZWU8=,iv:920IidIRrBdtblry6/v10evs/JPCki//oS+tcieB0g0=,tag:H+S6Dx8O7US3e+DN1BvhCQ==,type:str]
    pgp:
        - created_at: "2021-04-24T16:45:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAwAiC3F7Xe2/ehFoQJACW945mOeFuJZ3ufGRtNRUj/XtfRG
            p3FNkRXfsCjsqrG8UmT8+ydlJW45z1sD/b/2x5TI0Zsb2dZMor4Hxq/vxetKf/hi
            3ab8CglzxUKR8LI2qDoiVhy3jb4iGgox/Gaj5tGCvum9w2TR1WHu1RbQbFfcvba/
            sXge+wokuy5FiIHUiPFRrsDYIoKm6gycRajHmxf0aNBtMgXzBOAEuhfxnvFG0QhX
            d0R22cj6YEoC/6uagNsUvux1IgbV9zTyZPVPInt60aIRYKPvgpox5Pl9GLc15Gk2
            ZN2+Uf6unkaANZHTftHl7/i0lq935NTU1MJ1hlP0rhBWAmniM2tpJDl+VpGhY/vu
            lrmTCWOg0sPvRPp1YX/+wlX90ExFzxmcBsQkxmafTk+NuWCXtdXPG2juA3R44lQh
            Z599jtWDvhgcxGBfxjf3Yd516kpyuyGPslqWHbWJFDVo/8/Usxrj8YJxwan8geY5
            n7AK4ic0F3Oqae9NBrWmDADB6RlQ1+rpzXO1Iu/d/0XbC27Y771uQdCqcTS0/ks9
            TcBraKGHW9fsd0nCQ+GvnqV50EbOB/FnwD07/f+m0rZMGcpXZo3s3qB57vk9P/v7
            6lKuzrvtQFCqR2SapPz2/5gRk8kFh15mui2C9I0CDM2jcMYGLKPxq/36/eSe2zw9
            C+fqISoU3v6/q4noJAFEBaWfVD2TesxvMLv+yX7G1l6XhHFVADo4ngsFSDy5Qo1G
            SLrQE5ZS3EIgjTrG46iHxkSvZLmg6rYcErvZpdKcrwZcJkfV9VcYfP/QRP0Y5PyN
            mYWQGgryqhDxaYawA5o9y4zD83/D9qWpYd/oht7RgXJ304gXXyAe0j1vNZe+CknW
            N+RYp+XaeNAw38VEvsHPfRngZlJBU43QVdREUtfzmtXC4GUNhUb/s/YJD7ng5RUN
            Q9LjKg/m1wOkCPQhSK8rVivt353vx5ylS6L9L5aFtk3v6683Cn8jj4CH9LVqgjT/
            b38gxSJ7DP0IbFfMA2N5TI/SXAEnjNg9l4EYJ5/sEm1twrncF/bRwz7uMGB5C1is
            dRkWIDk10V4dHHgUUh9ppq2lW7YjbV5JVhHwXaPbpepZybTLan2QRwijak2tdn/J
            uLBfaDYIgiyL/JpJ4CL5
            =yPdo
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    namespace: ingress-system
    name: cloudflare-secret
type: Opaque
data:
    cloudflare_api_token: ENC[AES256_GCM,data:5Wqyiooc5aJEUbEHd4YeWMxRAU2J5mNKsrhRq6PoxcR/qIy23sR8/M4jADfK5WYQzzyTwN64Qfk=,iv:bWr/Pd4EBgoJAcoFW1+3H1InBfWqZOBDdy5KrbVsxjw=,tag:Nm0An3OBXi5UDB6jQkecOQ==,type:str]
    #ENC[AES256_GCM,data:aAOp+YHU0J4Rkl33x7dsb1DIITwWpdlL5T6+eQ0AC4V7fk6bat8DGoo=,iv:gHOprak2TO2JLGb80gOWQbQDXCx40uFWs3CZRxnuFtg=,tag:l/Lhko5+mJgDf4EU3gOwaA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-24T16:45:28Z"
    mac: ENC[AES256_GCM,data:fBjDQdnhxkCCJ14mVQdEws591INulAkQgjeCj4sjkqncOj/luXR9tr0V8mPHvR2Kvd6/IvbW5DZ339oTu+Jl0nd2UUk338rb1mGkMOxFm5xQFXF/94wOCVgeI0fYIMm3k1vPorCQppwcNcO4PN2qclOkT6toxOrGZ2viIOqZWU8=,iv:920IidIRrBdtblry6/v10evs/JPCki//oS+tcieB0g0=,tag:H+S6Dx8O7US3e+DN1BvhCQ==,type:str]
    pgp:
        - created_at: "2021-04-24T16:45:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQMOA7Xwm0UuZgqEEAwAiC3F7Xe2/ehFoQJACW945mOeFuJZ3ufGRtNRUj/XtfRG
            p3FNkRXfsCjsqrG8UmT8+ydlJW45z1sD/b/2x5TI0Zsb2dZMor4Hxq/vxetKf/hi
            3ab8CglzxUKR8LI2qDoiVhy3jb4iGgox/Gaj5tGCvum9w2TR1WHu1RbQbFfcvba/
            sXge+wokuy5FiIHUiPFRrsDYIoKm6gycRajHmxf0aNBtMgXzBOAEuhfxnvFG0QhX
            d0R22cj6YEoC/6uagNsUvux1IgbV9zTyZPVPInt60aIRYKPvgpox5Pl9GLc15Gk2
            ZN2+Uf6unkaANZHTftHl7/i0lq935NTU1MJ1hlP0rhBWAmniM2tpJDl+VpGhY/vu
            lrmTCWOg0sPvRPp1YX/+wlX90ExFzxmcBsQkxmafTk+NuWCXtdXPG2juA3R44lQh
            Z599jtWDvhgcxGBfxjf3Yd516kpyuyGPslqWHbWJFDVo/8/Usxrj8YJxwan8geY5
            n7AK4ic0F3Oqae9NBrWmDADB6RlQ1+rpzXO1Iu/d/0XbC27Y771uQdCqcTS0/ks9
            TcBraKGHW9fsd0nCQ+GvnqV50EbOB/FnwD07/f+m0rZMGcpXZo3s3qB57vk9P/v7
            6lKuzrvtQFCqR2SapPz2/5gRk8kFh15mui2C9I0CDM2jcMYGLKPxq/36/eSe2zw9
            C+fqISoU3v6/q4noJAFEBaWfVD2TesxvMLv+yX7G1l6XhHFVADo4ngsFSDy5Qo1G
            SLrQE5ZS3EIgjTrG46iHxkSvZLmg6rYcErvZpdKcrwZcJkfV9VcYfP/QRP0Y5PyN
            mYWQGgryqhDxaYawA5o9y4zD83/D9qWpYd/oht7RgXJ304gXXyAe0j1vNZe+CknW
            N+RYp+XaeNAw38VEvsHPfRngZlJBU43QVdREUtfzmtXC4GUNhUb/s/YJD7ng5RUN
            Q9LjKg/m1wOkCPQhSK8rVivt353vx5ylS6L9L5aFtk3v6683Cn8jj4CH9LVqgjT/
            b38gxSJ7DP0IbFfMA2N5TI/SXAEnjNg9l4EYJ5/sEm1twrncF/bRwz7uMGB5C1is
            dRkWIDk10V4dHHgUUh9ppq2lW7YjbV5JVhHwXaPbpepZybTLan2QRwijak2tdn/J
            uLBfaDYIgiyL/JpJ4CL5
            =yPdo
            -----END PGP MESSAGE-----
          fp: B5F09B452E660A84
    encrypted_regex: (^data$|^stringData$|user|[Pp]assword|userDatabase)
    version: 3.7.1
